### ISSUE TITLE
希望部署过程能删除bucket中不再需要的对象

### ISSUE THREAD

**Issue by haowang02** [sdlzhd/hexo-deployer-cos#11]
例如前一次部署后，bucket中有图片img/a.jpg
修改博客后img/a.jpg不再需要，于是我在本地将其删除
希望部署后bucket中img/a.jpg也能对应删除

如果没有类似的操作，bucket中不能被覆盖的废弃文件会越来越多，只能手动清空bucket来清理这些没有用的文件

**Comment by sdlzhd** [comment]
通过配置部署参数，提供该功能，例如

```yml
deploy:
  type: cos
  xxx: [local|remote]
```

标识文件以远程还是本地为准

该功能可于3月份发布
